name: CI

on:
  push:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nasm build-essential valgrind
    
    - name: Build
      run: make all
    
    - name: Run unit tests
      run: |
        echo "Running comprehensive unit tests..."
        ./build/unit_tests
    
    - name: Run integration tests
      run: |
        echo "Running integration tests..."
        ./build/test_runner
    
    - name: Run benchmarks
      run: |
        echo "Running performance benchmarks..."
        ./build/benchmark
    
    - name: Memory check - Unit tests
      run: |
        echo "Testing unit tests for memory leaks..."
        valgrind --leak-check=full --error-exitcode=1 ./build/unit_tests
    
    - name: Memory check - Integration tests
      run: |
        echo "Testing integration tests for memory leaks..."
        valgrind --leak-check=full --error-exitcode=1 ./build/test_runner
